// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/projects/[projectId]" | "/projects/[projectId]/assets" | "/projects/[projectId]/canvas" | "/projects/[projectId]/canvas/layers/[layerSetId]" | "/projects/[projectId]/export" | "/workspace" | "/workspace/aigc" | "/workspace/aigc/acceptance" | "/workspace/aigc/pipelines/[pipelineId]" | "/workspace/aigc/pipelines/[pipelineId]/nodes/[nodeId]/layers" | "/workspace/aigc/pipelines/[pipelineId]/nodes/[nodeId]/timeline" | "/workspace/aigc/templates/[templateId]" | "/workspace/assets" | "/workspace/projects" | "/workspace/tools"
type PageRoutes = never
type LayoutRoutes = "/" | "/workspace" | "/workspace/aigc"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/projects/[projectId]": { "projectId": string; }
  "/projects/[projectId]/assets": { "projectId": string; }
  "/projects/[projectId]/canvas": { "projectId": string; }
  "/projects/[projectId]/canvas/layers/[layerSetId]": { "projectId": string; "layerSetId": string; }
  "/projects/[projectId]/export": { "projectId": string; }
  "/workspace": {}
  "/workspace/aigc": {}
  "/workspace/aigc/acceptance": {}
  "/workspace/aigc/pipelines/[pipelineId]": { "pipelineId": string; }
  "/workspace/aigc/pipelines/[pipelineId]/nodes/[nodeId]/layers": { "pipelineId": string; "nodeId": string; }
  "/workspace/aigc/pipelines/[pipelineId]/nodes/[nodeId]/timeline": { "pipelineId": string; "nodeId": string; }
  "/workspace/aigc/templates/[templateId]": { "templateId": string; }
  "/workspace/assets": {}
  "/workspace/projects": {}
  "/workspace/tools": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/workspace": never
  "/workspace/aigc": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
