// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/[projectId]/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/assets">> = Specific
  const handler = {} as typeof import("../../../app/projects/[projectId]/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/[projectId]/canvas/layers/[layerSetId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/canvas/layers/[layerSetId]">> = Specific
  const handler = {} as typeof import("../../../app/projects/[projectId]/canvas/layers/[layerSetId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/[projectId]/canvas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/canvas">> = Specific
  const handler = {} as typeof import("../../../app/projects/[projectId]/canvas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/[projectId]/export/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/export">> = Specific
  const handler = {} as typeof import("../../../app/projects/[projectId]/export/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../../app/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workspace/aigc/acceptance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/aigc/acceptance">> = Specific
  const handler = {} as typeof import("../../../app/workspace/aigc/acceptance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workspace/aigc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/aigc">> = Specific
  const handler = {} as typeof import("../../../app/workspace/aigc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workspace/aigc/pipelines/[pipelineId]/nodes/[nodeId]/layers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/aigc/pipelines/[pipelineId]/nodes/[nodeId]/layers">> = Specific
  const handler = {} as typeof import("../../../app/workspace/aigc/pipelines/[pipelineId]/nodes/[nodeId]/layers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workspace/aigc/pipelines/[pipelineId]/nodes/[nodeId]/timeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/aigc/pipelines/[pipelineId]/nodes/[nodeId]/timeline">> = Specific
  const handler = {} as typeof import("../../../app/workspace/aigc/pipelines/[pipelineId]/nodes/[nodeId]/timeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workspace/aigc/pipelines/[pipelineId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/aigc/pipelines/[pipelineId]">> = Specific
  const handler = {} as typeof import("../../../app/workspace/aigc/pipelines/[pipelineId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workspace/aigc/templates/[templateId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/aigc/templates/[templateId]">> = Specific
  const handler = {} as typeof import("../../../app/workspace/aigc/templates/[templateId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workspace/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/assets">> = Specific
  const handler = {} as typeof import("../../../app/workspace/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace">> = Specific
  const handler = {} as typeof import("../../../app/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workspace/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/projects">> = Specific
  const handler = {} as typeof import("../../../app/workspace/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workspace/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/tools">> = Specific
  const handler = {} as typeof import("../../../app/workspace/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workspace/aigc/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/workspace/aigc">> = Specific
  const handler = {} as typeof import("../../../app/workspace/aigc/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workspace/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/workspace">> = Specific
  const handler = {} as typeof import("../../../app/workspace/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
